### ISSUE TITLE
Unable to save settings

### ISSUE THREAD

**Issue by RadTechDad** [shinobu254/sd-civitai-browser-plus#1]
The first time I did a search, I saved the settings as default.

Now, i'm trying to save new settings as default and I keep getting the following error:

`CivitAI Browser+: Cannot save settings, failed to open "<_io.TextIOWrapper name='D:\\stable-diffusion-webui\\ui-config.json' mode='r' encoding='cp1252'>"
Please try to manually repair the file or remove it to reset settings.`

I tried deleting the file, restarting stable diffusion, and then going back to change settings, but I still keep getting this error.

**Comment by shinobu254** [comment]
> The first time I did a search, I saved the settings as default.
> 
> Now, i'm trying to save new settings as default and I keep getting the following error:
> 
> `CivitAI Browser+: Cannot save settings, failed to open "<_io.TextIOWrapper name='D:\\stable-diffusion-webui\\ui-config.json' mode='r' encoding='cp1252'>" Please try to manually repair the file or remove it to reset settings.`
> 
> I tried deleting the file, restarting stable diffusion, and then going back to change settings, but I still keep getting this error.

I'm sorry for the inconvenience, this plugin is outdated and only works on a stable diffusion v1.6 modified by me

you can visit the original repository : https://github.com/BlafKing/sd-civitai-browser-plus

**Comment by RadTechDad** [comment]
Thank you!
